### ISSUE TITLE
SolverState snapshot fails when using momentum

### ISSUE THREAD

**Issue by lucastheis** [Russell91/nlpcaffe#2] opened 2015-04-10 14:47 UTC
Hi Russell, I'm training a large network with many shared parameters and your modifications have already been very helpful for that. But when I try to train *with momentum* I get the following error as soon as caffe is trying to save the solver's state. Any ideas?

```
I0410 14:38:16.953932   429 solver.cpp:334] Snapshotting to results/supervised/_iter_100.caffemodel
I0410 14:38:19.744149   429 solver.cpp:342] Snapshotting solver state to results/supervised/_iter_100.solverstate
*** Aborted at 1428676700 (unix time) try "date -d @1428676700" if you are using GNU date ***
PC: @     0x7ffb9e6345e2 caffe::BlobProto::SerializeWithCachedSizesToArray()
*** Error in `/opt/caffe/build/tools/caffe': malloc(): memory corruption: 0x0000000008519530 ***
Aborted (core dumped)
```

 Thanks!

**Comment by Russell91** [comment] 2015-04-10 22:26
Okay, I'm looking into this. Are you using the SGD solver or the Adagrad/Nesterov.

**Comment by lucastheis** [comment] 2015-04-11 09:38
I'm using SGD.

**Comment by Russell91** [comment] 2015-04-11 10:12
Hmm, I've tested with SGD and I'm just not able to reproduce this. You have two options:

1) If you want to debug this further, recompile with the DEBUG option in your Makefile.config and then train with `gdb -ex=r --args ./build/tools/caffe train --solver=./examples/language_model/solver.prototxt`. When you get the error, type `bt`, and paste the snapshot below.

2) Avoid writing the .solverstate files when using the momentum. The .caffemodel files contain all of the valuable information anyway. The easiest way to do this is to comment out the following lines in src/caffe/solver.cpp:

    //SolverState state;
    //SnapshotSolverState(&state);
    //state.set_iter(iter_ + 1);
    //state.set_learned_net(model_filename);
    //state.set_current_step(current_step_);
    //snapshot_filename = filename + ".solverstate";
    //LOG(INFO) << "Snapshotting solver state to " << snapshot_filename;
    //WriteProtoToBinaryFile(state, snapshot_filename.c_str());

You'll then be able to resume training with --weights=./path/to/lm_iter_100.caffemodel instead of the --solver=... command. This is preferable also in that it will allow you to resume training on nets with different RNN sequence lengths.

If anyone else encounters this issue, please just notify me and hopefully we can get a repro.

**Comment by lucastheis** [comment] 2015-04-11 10:21
Thanks for the hints and for getting so quickly on this.

I was able to reproduce this on different machines running different Docker containers and on the CPU/GPU, so that I'm guessing it's not a hardware/environment issue but rather my model or solver file that's causing trouble. I will try to come up with a minimal example that produces this error.

**Comment by lucastheis** [comment] 2015-04-12 11:41
The problem only seems to occur with very large models. It might be related to the problem that occurs when a .caffemodel file reaches 2GB (BVLC/caffe#2006), since that is also the regime where I encounter problems with .solverstate files. Trying to store the history necessary for momentum in the .solverstate file probably pushes it over some file size limit.

**Comment by Russell91** [comment] 2015-04-12 18:32
Okay, yea if you noticed I was the one that opened that Caffe issue. I almost suggested that the size limit could be causing the problem, but didn't as you got a different error than I did. I'm going to mark this as closed for now. This is why Caffe is moving towards things like HDF5,

**Closed by Russell91** 2015-04-12 18:32 UTC

**Comment by Russell91** [comment] 2015-04-12 19:54
Also, fwiw I checked the size of the .solverstate on some large models with momentum on and it is about 2.5x bigger than the .caffemodel. In the caffe main branch, this would be 30x bigger due to duplicated shared parameters. But I'm not sure what the source of the 2.5x is - Caffe shouldn't be allocating memory for histories if they aren't ever being used. If you look into this, you might be able to avoid the crashes you're getting.

**Comment by tarunsharma1** [comment] 2016-07-21 18:19
I was also getting this error....fixed it by changing mode to HDF5
For any other users with this issue add the line to your solver.prototxt


snapshot_format: HDF5
